# Generated by Django 3.1.6 on 2021-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, verbose_name='Organisation name / Organisationsname')),
                ('org_number', models.CharField(max_length=255, verbose_name='Organisations N° / Organisations Nr.')),
                ('org_website', models.CharField(max_length=255, verbose_name='Webseite / Webseite')),
                ('org_primary_phone', models.CharField(max_length=255, verbose_name='Primary phone / primäres Telefon')),
                ('org_add_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional name / Org. Namenszusatz')),
                ('org_fax', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fax')),
                ('org_member_of', models.CharField(blank=True, max_length=255, null=True, verbose_name='Member of / Mitglied von')),
                ('org_another_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Another phone / anderes Telefon')),
                ('org_staff', models.CharField(blank=True, max_length=255, null=True, verbose_name='Staff / Mitarbeiter')),
                ('org_primary_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary email / primäre E-Mail')),
                ('org_another_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Another email / andere E-Mail')),
                ('org_ownership', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ownership / Eigentümer')),
                ('org_sector', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sector / Branche')),
                ('org_evaluation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Evaluation / Wertung')),
                ('org_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type / Typ')),
                ('org_ust_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='UST. N° / Ust. Nr.')),
                ('org_email_opt_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email OPT from / E-Mail Opt. aus')),
                ('org_yearly_revenue', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yearly revenue / jährlicher Umsatz')),
                ('org_responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsible / zuständig')),
                ('org_inform_owners', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inform owners / Besitzer informieren')),
                ('org_changed', models.CharField(blank=True, max_length=255, null=True, verbose_name='changed / geändert')),
                ('org_created', models.CharField(blank=True, max_length=255, null=True, verbose_name='created / erstellt')),
                ('org_most_recently_amended_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='Most recently amended by / zuletzt geändert durch')),
                ('org_created_from_lead', models.CharField(blank=True, max_length=255, null=True, verbose_name='Created from lead / aus Lead erstellt')),
                ('org_invoice_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice address / Rechnungsadresse')),
                ('org_shipping_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping address / Lieferadresse')),
                ('org_invoice_po_box', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice PO Box / Rechnung Postfach')),
                ('org_delivery_mailbox', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery mailbox / Lieferung Postfach')),
                ('org_invoice_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Place / Rechnung Ort')),
                ('org_delivery_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Place / Lieferung Ort')),
                ('org_invoice_federal_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Federal State / Rechnung Bundesland')),
                ('org_delivery_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery State / Lieferung Bundesland')),
                ('org_Invoice_postal_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice postal code / Rechnung PLZ')),
                ('org_delivery_zip_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery zip code / Lieferung PLZ')),
                ('org_invoice_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice country / Rechnung Land')),
                ('org_delivery_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery country / Lieferung Land')),
                ('org_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description / Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
