# Generated by Django 3.1.6 on 2021-03-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_latitude',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_longitude',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5, verbose_name='Longitude'),
        ),
    ]
