# Generated by Django 3.1.6 on 2021-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_auto_20210303_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='changed / geändert'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created / erstellt'),
        ),
    ]
