# Generated by Django 3.1.6 on 2021-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_auto_20210303_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_latitude',
            field=models.DecimalField(decimal_places=10, default='0.00', max_digits=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_longitude',
            field=models.DecimalField(decimal_places=10, default='0.00', max_digits=20, verbose_name='Longitude'),
        ),
    ]
