# Generated by Django 3.1.6 on 2021-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_auto_20210303_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_latitude',
            field=models.DecimalField(blank=True, decimal_places=10, default='0.00', max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_longitude',
            field=models.DecimalField(blank=True, decimal_places=10, default='0.00', max_digits=20, null=True, verbose_name='Longitude'),
        ),
    ]
