# Generated by Django 3.1.6 on 2021-03-13 13:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_auto_20210303_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_org_name', models.CharField(max_length=255, verbose_name='sub organisation name')),
                ('country', models.CharField(max_length=255, verbose_name='country')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, default='0.00', max_digits=20, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, default='0.00', max_digits=20, null=True, verbose_name='Longitude')),
                ('telephone', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(16)], verbose_name='telephone')),
                ('fax', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(16)], verbose_name='fax')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('web', models.CharField(blank=True, max_length=255, null=True, verbose_name='web site')),
                ('ceo', models.CharField(blank=True, max_length=255, null=True, verbose_name='CEO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_app.organisation', verbose_name='Organisation name')),
            ],
        ),
    ]
