# Generated by Django 3.1.6 on 2021-03-14 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_auto_20210313_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborganisation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, default='0.00', max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='suborganisation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, default='0.00', max_digits=30, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='suborganisation',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_orgs', to='map_app.organisation', verbose_name='Organisation name'),
        ),
    ]
