# Generated by Django 3.1.6 on 2021-03-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0009_auto_20210314_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='org_filter_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Filter name'),
        ),
    ]
