# Generated by Django 3.1.6 on 2021-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0011_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='filtre_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='path',
            field=models.TextField(max_length=5000, verbose_name='path'),
        ),
    ]
