# Generated by Django 3.1.6 on 2021-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0012_auto_20210317_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_latitude',
            field=models.DecimalField(blank=True, decimal_places=20, default='0.00', max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_longitude',
            field=models.DecimalField(blank=True, decimal_places=20, default='0.00', max_digits=30, null=True, verbose_name='Longitude'),
        ),
    ]
