# Generated by Django 3.1.6 on 2021-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0013_auto_20210325_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='level',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='suborganisation',
            name='level',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
