# Generated by Django 3.1.6 on 2021-03-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0016_auto_20210327_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Webseite / Webseite'),
        ),
    ]
