# Generated by Django 3.1.6 on 2021-04-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0017_auto_20210327_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborganisation',
            name='org',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='SubOrganisation',
        ),
    ]
