# Generated by Django 3.1.6 on 2021-04-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0018_auto_20210402_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='org_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_country', to='map_app.countries'),
        ),
    ]
