# Generated by Django 3.1.6 on 2021-04-08 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0019_orgs_org_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='org_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='map_app.countries'),
        ),
    ]
