# Generated by Django 3.1.6 on 2021-04-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0020_auto_20210408_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgs',
            name='org_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_country', to='map_app.countries'),
        ),
    ]
