# Generated by Django 3.1.6 on 2021-04-08 17:50

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0021_auto_20210408_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
