# Generated by Django 3.1.6 on 2021-04-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0022_testupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='testupload',
            name='new_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
