# Generated by Django 3.1.6 on 2021-04-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0023_testupload_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='order_by',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
