# Generated by Django 3.1.6 on 2021-04-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0024_orgs_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgs',
            name='about_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='About Link'),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='order_by',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='orgs',
            name='org_description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description / Beschreibung'),
        ),
    ]
