# Generated by Django 3.1.6 on 2021-04-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0025_auto_20210409_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUpload',
        ),
    ]
