# Generated by Django 3.1.6 on 2021-04-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0026_delete_testupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, default='0.00', max_digits=30, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='countries',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, default='0.00', max_digits=30, null=True, verbose_name='Longitude'),
        ),
    ]
