# Generated by Django 3.1.6 on 2021-02-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20201205_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user_picture/user_img.png', null=True, upload_to='user_picture/'),
        ),
    ]
